openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
servers:
  - url: http://localhost:3001/api
paths:
  /auth/register:
    post:
      summary: Register user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [lastName, name, mail, password]
              properties:
                lastName:
                  type: string
                  example: Gegout
                name:
                  type: string
                  example: Edgar
                mail:
                  type: string
                  example: edgar@mail.com
                password:
                  type: string
                  example: Edgar1011
      responses:
        201:
          description: User registered
  /auth/login:
    post:
      summary: Login user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [mail, password]
              properties:
                mail:
                  type: string
                  example: edgar@mail.com
                password:
                  type: string
                  example: Edgar1011
      responses:
        200:
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /auth/logout:
    post:
      summary: Logout user
      tags:
        - Auth
      responses:
        200:
          description: Logout success
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
